spring:
  application:
    name: body-simulator
  profiles:
    active: dev
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST:47.102.196.250}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:postgres}"
    username: "${POSTGRES_USERNAME:postgres}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver

server:
  port: 8089
  servlet:
    context-path: /
